### PR TITLE
Adding overloads for Register(), RegisterSingleton() accepting params Assembly[]

### LINKED ISSUE #450: Batch / Automatic registration signature mismatch for Register() and RegisterSingleton()
The code from the [doc](http://simpleinjector.readthedocs.io/en/latest/advanced.html#batch-registration):

``` c#
container.Register(typeof(IValidator<>), new[] { typeof(IValidator<>).Assembly });
```

uses this method:

``` c#
public void Register(Type openGenericServiceType, IEnumerable<Assembly> assemblies)
```

But this code (which works fine for the 'standard' registration):

``` c#
container.RegisterSingleton(typeof(IValidator<>), new[] { typeof(IValidator<>).Assembly });
```

uses wrong (unexpected) method:

``` c#
public void RegisterSingleton(Type serviceType, object instance);
```

Is it possible to add the appropriate overload for `RegisterSingleton()` as well?

P.S. Few more ideas:

``` c#
public void Register(Type openGenericServiceType, params Assembly[] assemblies);

public void RegisterSingleton(Type openGenericServiceType, params Assembly[] assemblies);
```

### PR DESCRIPTION
**Pull request by abatishchev**
- Adding batch Register() overload accepting `params Asesmbly[]`
- Adding batch RegisterSingleton() overload accepting `params Asesmbly[]`, `IEnumerable<Asesmbly>`

Closes #450

### CODE REVIEW

**Comment by abatishchev** [comment]
Interestingly `Register(,,params Asesmbly[])` got automatically covered by tests because compiler preferred this overload over the existing one.

**Comment by abatishchev** [comment]
Also AppVeyor build is broken irrespective this pr.

**Comment by dotnetjunkie** [comment]
Never mind AppVeyor. It is broken. Haven't hadd any time to fix it.

**Comment by dotnetjunkie** [comment]
There is a reason why there is no `Register(Type, params Assembly[])` but only a `Register(Type, IEnumerable<Assembly>)`.

The reason is that the API always puts the `Lifestyle` parameter as last argument in the method. For instance:

``` c#
Register(Type, Type);
Register(Type, Type, Lifestyle);

Register<TService>(Func<TService>);
Register<TService>(Func<TService>, Lifestyle);

Register(Type, IEnumerable<Assembly>);
Register(Type, IEnumerable<Assembly>, Lifestyle);

Register(Type, IEnumerable<Type>);
Register(Type, IEnumerable<Type>, Lifestyle);
```

The addition of a `params` version of the `Register` method would break with this convention, because it would prevent the `Lifestyle` to be the last parameter.

Because this would lead to confusion and sometimes even compile errors, with the knowledge that most of the time, the list of assemblies would come from a source that would be an array or `IEnumerable` (instead of being a hand-defined list), I opted for not including a `params` list.

An overload accepting a single `Assembly` might make more sense (but I have to think about this for a bit)

```
Register(Type, Assembly)
Register(Type, Assembly, Lifestyle)
```

**Comment by abatishchev** [comment]
For Web Api project it'd be likely sufficient to pass single (current) assembly.

**Comment by abatishchev** [comment]
I can remove the change for Register(). Do RegisterSingleton() look good to you?

**Comment by dotnetjunkie** [comment]
`RegisterSingleton()` looks fine to me.

I would like you to do 3 things:

- Sign the [CLA](https://simpleinjector.readthedocs.io/en/latest/contribute.html)
- Remove the change for `Register()`
- Create a pull request on the [v4.1.x branch](https://github.com/simpleinjector/SimpleInjector/tree/v4.1.x).

If you do that, I'll approve your PR.

**Comment by abatishchev** [comment]
Sure but on
> Sign the CLA
Let me check with Microsoft CELA on this, I'll come back as fast as I can.

**Comment by abatishchev** [comment]
To fully follow the procedure, I tried to build locally using build.bat. Do you know how to deal with this:

> The imported project "D:\SandcastleHelpFileBuilder.targets" was not found.

and this (tons of them):

>The system cannot find the path specified.
>The system cannot find the path specified.
>The system cannot find the path specified.

**Comment by dotnetjunkie** [comment]
You can exclude the documentation project, or install SHFB (I Think it's described in the docs). Excluding the doc project is the easiest thing to do. You don't need it.

**Comment by abatishchev** [comment]
Submitting the contribution for a review. Hopefully won't take too long, But still, you know, Microsoft legal organization :)

**Comment by dotnetjunkie** [comment]
Thanks for taking the time to go through legal. I know it is challenging in a big organization.

It's unfortunate to require these kinds of legal measures, but it is important for the health of the project.

**Comment by abatishchev** [comment]
- [x] Sign the CLA
- [x] Remove the change for Register()
- [x] Create a pull request on the v4.1.x branch.

**Comment by abatishchev** [comment]
Sorry for delayed response. I know this project requires from you almost full-time attention. I try to balance programming with the rest of my life somehow :))

[You've asked](#issuecomment-323447810) to remove those overloads to do not break the existing arguments order convention. Tell me, I can add back in that or other way.

**Comment by dotnetjunkie** [comment]
Hmmm, yes.... let me think about that for a while. I'll get back to you.

> this project requires from you almost full-time attention. I try to balance programming with the rest of my life somehow

Don't worry, I won't hold it against you that you actually have a life :)

**Comment by dotnetjunkie** [comment]
After doing some testing, I think it is okay if we add some Batch-registration overloads for `Register` as well, but I'll create a new issue for this.

Thanks for your pull request!

**Pull request merged**
