### PR TITLE
Using full exception in ConfigurationInvalidCreatingInstanceFailed

### PR DESCRIPTION
**Pull request by abatishchev**
Currently `ConfigurationInvalidCreatingInstanceFailed` includes only the exception message. For cases, such as ArgumentException occurred deep inside service's class tree, it doesn't provide enough information.

For instance, for the code like this:

```csharp
var container = ContainerConfig.CreateContainer();

Action action = () => container.Verify(VerificationOption.VerifyOnly);

action.ShouldNotThrow();
```
The exception would be this:
```
at FluentAssertions.Execution.FallbackTestFramework.Throw(String message) in D:\Workspaces\FluentAssertions\Src\Shared\Execution\FallbackTestFramework.cs:line 21
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in D:\Workspaces\FluentAssertions\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in D:\Workspaces\FluentAssertions\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in D:\Workspaces\FluentAssertions\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Specialized.ActionAssertions.ShouldNotThrow(String because, Object[] reasonArgs) in D:\Workspaces\FluentAssertions\Src\Core\Specialized\ActionAssertions.cs:line 100
   at FluentAssertions.AssertionExtensions.ShouldNotThrow(Action action, String because, Object[] reasonArgs) in D:\Workspaces\FluentAssertions\Src\Shared\AssertionExtensions.Actions.cs:line 125
   at WebJobs.Tests.ContainerConfigTest.Container_Verify_Should_Not_Throw_Exception() in WebJobs.Tests\ContainerConfigTest.cs:line 21
Result Message:	
FluentAssertions.Execution.AssertionFailedException:
Did not expect any exception, but found System.InvalidOperationException with message "The configuration is invalid. Creating the instance for type IAzureProductProvider failed. Value cannot be null.
Parameter name: authKey"
     at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
     at SimpleInjector.Container.VerifyInstanceCreation(InstanceProducer[] producersToVerify)
     at SimpleInjector.Container.VerifyThatAllRootObjectsCanBeCreated()
     at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
     at SimpleInjector.Container.Verify(VerificationOption option)
     at WebJobs.Tests.ContainerConfigTest.<>c__DisplayClass0_0.<Container_Verify_Should_Not_Throw_Exception>b__0() in WebJobs.Tests\ContainerConfigTest.cs:line 18
     at FluentAssertions.Specialized.ActionAssertions.ShouldNotThrow(String because, Object[] reasonArgs) in D:\Workspaces\FluentAssertions\Src\Core\Specialized\ActionAssertions.cs:line 96
```
Particularly:
>The configuration is invalid. Creating the instance for type IAzureProductProvider failed. Value cannot be null.
Parameter name: authKey

### CODE REVIEW

**Comment by abatishchev** [comment]
CI build has failed but it doesn't seem to be my fault :)

**Comment by dotnetjunkie** [comment]
The CI build is experimental. Appveyor can't build our code yet.

**Comment by dotnetjunkie** [comment]
I disagree with your change. The problem you have is caused by Fluent Assertions. Simple Injector throws an `InvalidOperationException` that wraps the original exception, while appending the inner exception's message to the new exception. Thereby preserving all exception details. By serializing the complete inner exception as part of the exception the exception message results in very ugly exception messages, making it actually harder for users to understand what is going on.

I think you should either send a pull request to Fluent Assertions just prevent using `ShouldNotThrow`. By simply letting the exception bubble out of the test method, your testing framework (or at least, MSTest does) will show you the complete exception details with inner exception details.

**Comment by abatishchev** [comment]
You're right, letting the exception bubble out of the test method provides much more useful information.

**Pull request closed without merging**
