### PR TITLE
Fix appveyor ci

### PR DESCRIPTION
**Pull request by hanabi1224**

### CODE REVIEW

**Comment by hanabi1224** [comment]
Looks like project setting is 'ignore appveyor.yml' on appveyor site, it passes on my fork project tho

**Comment by hanabi1224** [comment]
@dotnetjunkie  Can you change appveyor setting to respect yml file in repo?

**Comment by dotnetjunkie** [comment]
Let me get back to you on that.

**Comment by dotnetjunkie** [comment]
> Can you change appveyor setting to respect yml file in repo?

The `Ignore appveyor.yml` setting is currently _not_ checked.

**Comment by hanabi1224** [comment]
@dotnetjunkie  From the buddy build I can see msbuild version is v14, while the image i choose is v15, it's definitely using the appveyor.xml in the repo, I the build works perfectly for my branch,  I don't have permission to check your appveyor site settings but can you try deactivating this project and add it again?

msbuild "C:\projects\simpleinjector\src\SimpleInjector.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved

**Comment by dotnetjunkie** [comment]
>  can you try deactivating this project and add it again?

How can I achieve this?

**Comment by hanabi1224** [comment]
@dotnetjunkie  
image

**Comment by qujck** [comment]
What was the reasons for moving from coveralls to codecov

**Comment by dotnetjunkie** [comment]
We decided to remove app veyor integration from GitHub.

**Pull request closed without merging**
