### PR TITLE
Restore missing files to fix build

### PR DESCRIPTION
**Pull request by flcdrg**
Add NuGet reference for System.Web.Mvc 3.0.0.1

### CODE REVIEW

**Comment by dotnetjunkie** [comment]
Can you explain what changed in the `project.lock.json` files SimpleInjector.Extensions.ExecutionContextScoping/project.lock.json and
SimpleInjector.Extensions.LifetimeScoping/project.lock.json? I find it very hard to compare them with the original.

**Comment by dotnetjunkie** [comment]
Thank you for this PR. This pull request consist of two fixes. 1. Addition of missing files that caused the build to fail on any machine, and 2. changes to how MVC is referenced from the MVC integration package.

Because the PR consists of these two parts, I decided to reject the PR in itself, but I used the information to fix the missing files issue with checkin 2a6e906c4e96adc2560d9088209896bcbd4857e6. Since the change in MVC causes changes to the NuGet package, I created work item #218. It will be picked up in a later release.

**Comment by flcdrg** [comment]
No worries. Glad to get the fixes in either way :-)

You probably figured it out already, but I think the project.lock.json changes were done automatically by Visual Studio.

**Comment by dotnetjunkie** [comment]
The SimpleInjector.Integration.Web.Mvc NuGet package now references the Microsoft.AspNet.Mvc NuGet package instead of referencing System.Web.Mvc from the GAC. This changed will be rolled out with v3.2.

Since everything in this pull request has now been integrated, I'll close this PR.

Thank you for this PR.

**Pull request closed without merging**
