### PR TITLE
fix app

### PR DESCRIPTION
**Pull request by lobster2012-user**
*

### CODE REVIEW

**Comment by lobster2012-user** [comment]
Hello! 
@dotnetjunkie 
Unfortunately, I'm not sure that it helped. The problem, it seems to me, must be solved very simply.

**Comment by dotnetjunkie** [comment]
Yes, I think there's more to it than changing the VS version, but as we don't support `2015` any longer, it seemed safe to merge this PR.

**Comment by lobster2012-user** [comment]
The old version of msbuild  is still used.
https://ci.appveyor.com/project/simpleinjector/simpleinjector/builds/23021893
(Microsoft (R) Build Engine version 14.0.25420.1)

Perhaps you need to do another push in the master. Not sure.

#574 
I see @hanabi1224   also tried ...

**Comment by dotnetjunkie** [comment]
Yes, and @qujck tried to figure out what hanabi tried to achieve.

**Comment by lobster2012-user** [comment]
@dotnetjunkie 
I would add echo some-thing to see if the last appveyour is being used.

**Comment by lobster2012-user** [comment]
app
What about this setting?

**Comment by dotnetjunkie** [comment]
@qujck, do you know more about this?

I'm inclined to completely remove the build process, as I don't really know how to manage it, and it has proven to need a considerable amount of maintenance.

**Comment by qujck** [comment]
I agree, we don't release from this pipeline making it a useless overhead

**Comment by dotnetjunkie** [comment]
@qujck, I removed the webhook from the repository's settings, but the [pull requests tab](https://github.com/simpleinjector/SimpleInjector/pulls) still shows build failures. Do you know how to remove that?

**Comment by qujck** [comment]
That build is still connected to appveyor - would expect another build of the same branch to no longer show a status

**Comment by lobster2012-user** [comment]
I think that

**1.** Not used appveyor.yml
or not used correctly.
appveyor.bat is simply not correct.

**2.** I played with a `build working image`,
watching the ms build version change.

**3.**
2 tests failed, the first can be fixed. The second one needs to be ignored when building with appveyor, you have to correct appveyor

**4.** Without a normal CI, it will be difficult with PR ...

**5.** The fastest merging in my life, thank you.

**Pull request merged**
