### PR TITLE
adding check if registered method

### PR DESCRIPTION
**Pull request by lloydstockman**

### CODE REVIEW

**Comment by dotnetjunkie** [comment]
Simple Injector already contains this functionality by calling `container.GetRegistration(Type) != null`.

**Comment by dotnetjunkie** [comment]
What is the story behind the need for such an `IsRegistered` method?

**Comment by lloydstockman** [comment]
Oh sorry man didn't see that. I will use that instead thank you

**Comment by dotnetjunkie** [comment]
No problem.

**Comment by apmorton** [comment]
One way your proposed extension method falls short is that according to the docs `GetRegistration` locks the container.

Doesn't this mean you would be unable to write code like the following?
```
if (!container.IsRegistered<IService>()) {
    container.Register<IService, MyService>();
}
```

**Comment by dotnetjunkie** [comment]
Can you explain yout use case? Why do you want to do this?

**Comment by apmorton** [comment]
https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Ninject.Wpf/NinjectBootstrapper.cs#L156

This is an example usage from prism with the ninject implementation.
```c#
this.Kernel.RegisterTypeIfMissing<IServiceLocator, NinjectServiceLocatorAdapter>(true);
this.Kernel.RegisterTypeIfMissing<IModuleInitializer, ModuleInitializer>(true);
this.Kernel.RegisterTypeIfMissing<IModuleManager, ModuleManager>(true);
this.Kernel.RegisterTypeIfMissing<RegionAdapterMappings, RegionAdapterMappings>(true);
```

Basically they want to register default implementations only if the user hasn't already registered their own to 'override' the defaults.

I am going to be attempting to use SimpleInjector with Prism in the coming weeks, and the first thing that needs to be done is implement a prism bootstrapper for SimpleInjector - its not too complex, the only thing missing is being able to `RegisterTypeIfMissing` (this is not a functionality of ninject, but rather an extension method provided by Prism - but to implement it you need `IsRegistered`)

**Comment by dotnetjunkie** [comment]
I would normally not advice this model for normal application development, but with integration with frameworks that apply [Conforming Containers](http://blog.ploeh.dk/2014/05/19/conforming-container/) like Prism, there's probably no way around it. The way to do this in Simple Injector is to use the `ResolveUnregisteredType` event. Built on top of this event you can make the following extension method:

``` c#
public static void RegisterTypeIfMissing<TService, TImpl>(this Container container,
    Lifestyle lifestyle = null)
    where TImpl : class, TService
    where TService : class {
    container.ResolveUnregisteredType += (s, e) => {
        lifestyle = lifestyle ?? container.Options.LifestyleSelectionBehavior
            .SelectLifestyle(typeof(TService), typeof(TImpl));
        if (!e.Handled && e.UnregisteredServiceType == typeof(TService)) {
            e.Register(lifestyle.CreateRegistration<TService, TImpl>(container));
        }
    };
}
```

Another option is to make a conditional registration as follows:

``` c#
container.RegisterConditional<IModuleInitializer, ModuleInitializer>(c => !c.Handled);
```

This is much simpler, but the limitation here is that any possible previous registration is made conditional as well. In case the first registration is unconditional, Simple Injector will detect that the second (conditional) registration can never be applied and throws an exception when such registration takes place, because this would typically mean a misconfiguration.

**Pull request closed without merging**
