### PR TITLE
Update StringResources.cs

### PR DESCRIPTION
**Pull request by abatishchev**
Replacing `\n` with actual `Environment.NewLine`

### CODE REVIEW

**Comment by abatishchev** [comment]
Other option would be probably using `\r\n` rather than just `\n`.

**Comment by abatishchev** [comment]
@dotnetjunkie hey Steven, AppVeyor looks more dead than alive :)

**Comment by dotnetjunkie** [comment]
Yes, AppVayor isn't working for some time now :(

**Comment by dotnetjunkie** [comment]
Thanks for this pull request. Based on your changes I found some other places where \n was used. I decided to close your pull request and create a separate check-in with those changes as well.

Thanks for your pull request.

**Pull request closed without merging**
